version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
    volumes:
      - ./database/data.db:/app/database/data.db

